// Ghana Revenue System Data
// Administrative divisions and reference data

// Ghanaian Metropolitan, Municipal and District Assemblies (MMDAs)
// This is a comprehensive list of Ghana's administrative divisions
export const ghanaAssemblies = [
  // Greater Accra Region
  "Accra Metropolitan Assembly",
  "Tema Metropolitan Assembly",
  "Ga East Municipal Assembly",
  "Ga West Municipal Assembly",
  "Ga South Municipal Assembly",
  "Ga Central Municipal Assembly",
  "Ledzokuku Municipal Assembly",
  "Adenta Municipal Assembly",
  "Ashaiman Municipal Assembly",
  "La Dade Kotopon Municipal Assembly",
  "La Nkwantanang Madina Municipal Assembly",
  "Kpone Katamanso Municipal Assembly",
  "Ablekuma North Municipal Assembly",
  "Ablekuma West Municipal Assembly",
  "Ablekuma Central Municipal Assembly",
  "Ayawaso East Municipal Assembly",
  "Ayawaso North Municipal Assembly",
  "Ayawaso West Municipal Assembly",
  "Ayawaso Central Municipal Assembly",
  "Okaikwei North Municipal Assembly",
  "Korle Klottey Municipal Assembly",

  // Ashanti Region
  "Kumasi Metropolitan Assembly",
  "Obuasi Municipal Assembly",
  "Asante Akim North District Assembly",
  "Asante Akim South District Assembly",
  "Afigya Kwabre District Assembly",
  "Ahafo Ano North District Assembly",
  "Ahafo Ano South District Assembly",
  "Amansie Central District Assembly",
  "Amansie West District Assembly",
  "Atwima Kwanwoma District Assembly",
  "Atwima Mponua District Assembly",
  "Atwima Nwabiagya District Assembly",
  "Bekwai Municipal Assembly",
  "Bosome Freho District Assembly",
  "Bosomtwe District Assembly",
  "Ejisu Municipal Assembly",
  "Ejura Sekyedumase Municipal Assembly",
  "Kwabre East Municipal Assembly",
  "Mampong Municipal Assembly",
  "Offinso Municipal Assembly",
  "Offinso North District Assembly",
  "Sekyere Afram Plains District Assembly",
  "Sekyere Central District Assembly",
  "Sekyere East District Assembly",
  "Sekyere Kumawu District Assembly",
  "Sekyere South District Assembly",

  // Central Region
  "Cape Coast Metropolitan Assembly",
  "Abura Asebu Kwamankese District Assembly",
  "Agona East District Assembly",
  "Agona West Municipal Assembly",
  "Ajumako Enyan Essiam District Assembly",
  "Asikuma Odoben Brakwa District Assembly",
  "Assin North Municipal Assembly",
  "Assin South District Assembly",
  "Awutu Senya East Municipal Assembly",
  "Awutu Senya West District Assembly",
  "Effutu Municipal Assembly",
  "Ekumfi District Assembly",
  "Gomoa East District Assembly",
  "Gomoa West District Assembly",
  "Komenda Edina Eguafo Abirem Municipal Assembly",
  "Mfantseman Municipal Assembly",
  "Twifo Ati Mokwa District Assembly",
  "Twifo Hemang Lower Denkyira District Assembly",
  "Upper Denkyira East Municipal Assembly",
  "Upper Denkyira West District Assembly",

  // Eastern Region
  "New Juaben Municipal Assembly",
  "Nkawkaw Municipal Assembly",
  "Abuakwa North Municipal Assembly",
  "Abuakwa South Municipal Assembly",
  "Achiase District Assembly",
  "Akuapem North Municipal Assembly",
  "Akuapem South District Assembly",
  "Akyemansa District Assembly",
  "Asene Manso Akroso District Assembly",
  "Asuogyaman District Assembly",
  "Atiwa East District Assembly",
  "Atiwa West District Assembly",
  "Ayensuano District Assembly",
  "Birim Central Municipal Assembly",
  "Birim North District Assembly",
  "Birim South District Assembly",
  "Denkyembour District Assembly",
  "Fanteakwa District Assembly",
  "Kwaebibirem Municipal Assembly",
  "Kwahu Afram Plains North District Assembly",
  "Kwahu Afram Plains South District Assembly",
  "Kwahu East District Assembly",
  "Kwahu South District Assembly",
  "Kwahu West Municipal Assembly",
  "Lower Manya Krobo Municipal Assembly",
  "New Juaben North Municipal Assembly",
  "New Juaben South Municipal Assembly",
  "Nsawam Adoagyiri Municipal Assembly",
  "Okere District Assembly",
  "Suhum Municipal Assembly",
  "Upper Manya Krobo District Assembly",
  "Upper West Akim District Assembly",
  "West Akim Municipal Assembly",
  "Yilo Krobo Municipal Assembly",

  // Northern Region
  "Tamale Metropolitan Assembly",
  "Sagnarigu Municipal Assembly",
  "Gushegu Municipal Assembly",
  "Karaga District Assembly",
  "Kpandai District Assembly",
  "Kumbungu District Assembly",
  "Mion District Assembly",
  "Nanton District Assembly",
  "Nanumba North Municipal Assembly",
  "Nanumba South District Assembly",
  "Saboba District Assembly",
  "Savelugu Municipal Assembly",
  "Tatale Sanguli District Assembly",
  "Tolon District Assembly",
  "Yendi Municipal Assembly",
  "Zabzugu District Assembly",

  // Upper East Region
  "Bolgatanga Municipal Assembly",
  "Bawku Municipal Assembly",
  "Bongo District Assembly",
  "Builsa District Assembly",
  "Builsa South District Assembly",
  "Garu District Assembly",
  "Kassena Nankana Municipal Assembly",
  "Kassena Nankana West District Assembly",
  "Nabdam District Assembly",
  "Pusiga District Assembly",
  "Talensi District Assembly",
  "Tempane District Assembly",

  // Upper West Region
  "Wa Municipal Assembly",
  "Wa East District Assembly",
  "Wa West District Assembly",
  "Jirapa Municipal Assembly",
  "Lambussie Karni District Assembly",
  "Lawra District Assembly",
  "Nadowli Kaleo District Assembly",
  "Nandom Municipal Assembly",
  "Sissala East Municipal Assembly",
  "Sissala West District Assembly",
  "Daffiama Bussie Issa District Assembly",

  // Volta Region
  "Ho Municipal Assembly",
  "Keta Municipal Assembly",
  "Hohoe Municipal Assembly",
  "Adaklu District Assembly",
  "Afadjato South District Assembly",
  "Agotime Ziope District Assembly",
  "Akatsi North District Assembly",
  "Akatsi South District Assembly",
  "Anloga District Assembly",
  "Central Tongu District Assembly",
  "Ho West District Assembly",
  "Jasikan District Assembly",
  "Kadjebi District Assembly",
  "Ketu North Municipal Assembly",
  "Ketu South Municipal Assembly",
  "Kpando Municipal Assembly",
  "Krachi East Municipal Assembly",
  "Krachi Nchumuru District Assembly",
  "Krachi West District Assembly",
  "Nkwanta North District Assembly",
  "Nkwanta South Municipal Assembly",
  "North Dayi District Assembly",
  "North Tongu District Assembly",
  "South Dayi District Assembly",
  "South Tongu District Assembly",

  // Western Region
  "Sekondi Takoradi Metropolitan Assembly",
  "Tarkwa Nsuaem Municipal Assembly",
  "Ahanta West Municipal Assembly",
  "Aowin Municipal Assembly",
  "Bia East District Assembly",
  "Bia West District Assembly",
  "Bibiani Anhwiaso Bekwai Municipal Assembly",
  "Bodi District Assembly",
  "Ellembele District Assembly",
  "Jomoro Municipal Assembly",
  "Juaboso District Assembly",
  "Mpohor District Assembly",
  "Nzema East Municipal Assembly",
  "Prestea Huni Valley Municipal Assembly",
  "Sefwi Akontombra District Assembly",
  "Sefwi Wiawso Municipal Assembly",
  "Shama District Assembly",
  "Suaman District Assembly",
  "Wassa Amenfi Central District Assembly",
  "Wassa Amenfi East Municipal Assembly",
  "Wassa Amenfi West District Assembly",
  "Wassa East District Assembly",

  // Western North Region
  "Sefwi Wiawso Municipal Assembly",
  "Bibiani Anhwiaso Bekwai Municipal Assembly",
  "Bodi District Assembly",
  "Juaboso District Assembly",
  "Sefwi Akontombra District Assembly",
  "Suaman District Assembly",

  // Bono Region
  "Sunyani Municipal Assembly",
  "Berekum Municipal Assembly",
  "Dormaa Central Municipal Assembly",
  "Jaman North District Assembly",
  "Jaman South Municipal Assembly",
  "Sunyani West District Assembly",
  "Tain District Assembly",
  "Wenchi Municipal Assembly",
  "Banda District Assembly",
  "Dormaa East District Assembly",
  "Dormaa West District Assembly",

  // Bono East Region
  "Techiman Municipal Assembly",
  "Atebubu Amantin Municipal Assembly",
  "Kintampo North Municipal Assembly",
  "Kintampo South District Assembly",
  "Nkoranza North District Assembly",
  "Nkoranza South Municipal Assembly",
  "Pru East District Assembly",
  "Pru West District Assembly",
  "Sene East District Assembly",
  "Sene West District Assembly",

  // Ahafo Region
  "Goaso Municipal Assembly",
  "Asunafo North Municipal Assembly",
  "Asunafo South District Assembly",
  "Asutifi North District Assembly",
  "Asutifi South District Assembly",
  "Tano North Municipal Assembly",
  "Tano South Municipal Assembly",

  // North East Region
  "Nalerigu Municipal Assembly",
  "Bunkpurugu Nyankpanduri District Assembly",
  "Chereponi District Assembly",
  "East Mamprusi Municipal Assembly",
  "Mamprugu Moagduri District Assembly",
  "West Mamprusi Municipal Assembly",
  "Yunyoo Nasuan District Assembly",

  // Savannah Region
  "Damongo Municipal Assembly",
  "Bole District Assembly",
  "Central Gonja District Assembly",
  "East Gonja Municipal Assembly",
  "North Gonja District Assembly",
  "North East Gonja District Assembly",
  "Sawla Tuna Kalba District Assembly",
  "West Gonja District Assembly",

  // Oti Region
  "Dambai Municipal Assembly",
  "Guan District Assembly",
  "Jasikan District Assembly",
  "Kadjebi District Assembly",
  "Krachi East Municipal Assembly",
  "Krachi Nchumuru District Assembly",
  "Krachi West District Assembly",
  "Nkwanta North District Assembly",
  "Nkwanta South Municipal Assembly"
];

// Ghanaian Regions for reference
export const ghanaRegions = [
  "Greater Accra",
  "Ashanti",
  "Central",
  "Eastern",
  "Northern",
  "Upper East",
  "Upper West",
  "Volta",
  "Western",
  "Western North",
  "Bono",
  "Bono East",
  "Ahafo",
  "North East",
  "Savannah",
  "Oti"
];

// Payment methods available in Ghana
export const ghanaPaymentMethods = [
  { value: "cash", label: "Cash (GHS)" },
  { value: "mobile_money", label: "Mobile Money (MoMo)" },
  { value: "bank_transfer", label: "Bank Transfer" },
  { value: "card", label: "Card Payment" },
  { value: "check", label: "Check" }
];

// Collection types specific to Ghana's revenue system
export const collectionTypes = [
  { value: "revenue", label: "Revenue" },
  { value: "permit", label: "Permit" },
  { value: "license", label: "License" },
  { value: "fee", label: "Fee" },
  { value: "fine", label: "Fine" }
];